# -*- coding: utf-8 -*-
"""Copy of dsa210-part2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J3F-3a4bXJDgw8KG7DB3DGlPJWxeZrMs

DATA LOADİNG
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression


crime_index = pd.read_csv("World Crime Index .csv")
happiness_report = pd.read_csv("World Happiness Report up to 2022.csv")
school_enrollment = pd.read_csv("School enrollment, primary (% gross).csv",header=4)
life_expectancy = pd.read_csv("Life expectancy at birth, total (years).csv",header=4)

"""DATA STANDARDIZATION
*   Taking only the country and the values that is needed from the tables and
*   giving more meaningfull names and standarize the country column name
* Taking only the 2022 years value
* For the happines report: the values are separeted wih coma but we need to change it to the float format.
* In the crime index data: there is not only the countries; there are crime numbers by citiies so because of that from the city column we take the country name and we take the mean of it by the country using grouping we calculate crime index by country

"""

year = '2022'

happiness_report['Happiness_2022'] = happiness_report['Happiness score'].str.replace(',', '.').astype(float)
happiness_2022 = happiness_report[['Country', 'Happiness_2022']]
school_2022 = school_enrollment.rename(columns={'Country Name': 'Country'})[['Country', year]].rename(columns={year: 'Education_2022'})
life_2022 = life_expectancy.rename(columns={'Country Name': 'Country'})[['Country', year]].rename(columns={year: 'LifeExp_2022'})

crime_index['Country'] = crime_index['City'].str.split(',').str[-1].str.strip()
crime_country = crime_index.groupby('Country', as_index=False)['Crime Index'].mean()
crime_country = crime_country.rename(columns={'Crime Index': 'CrimeIndex_2022'})

"""MERGİNG DATA
* By usin the same country we merged all the 4 datas
"""

merged_data = (
    happiness_2022
    .merge(school_2022, on='Country', how='left')
    .merge(life_2022, on='Country', how='left')
    .merge(crime_country, on='Country', how='left')
)
display(merged_data)
turkey = merged_data[merged_data['Country'] == 'Turkey']
display(turkey)

# İn the display it can be seen that there are some NaN parts

"""MERGE AND STANDARİZE:
* Because in the previous there are some NaN parts for the turkey there need to be name standarization
* For all the data sets the writing style of 'Turkey' made is standarize to one writing style
* Afterwards it merged again by using new datas
* There are some missing values and these values are filled with mean of that column that get without Nan
"""

# İn the data there are some parts that Turkey is writen differently
# For that the name is replaced and standarized to the Turkey
## happiness_2022['Country'] = happiness_2022['Country'].str.strip().replace({'Turkiye': 'Turkey', 'Türkiye': 'Turkey'})
school_2022['Country'] = school_2022['Country'].str.strip().replace({'Turkiye': 'Turkey', 'Türkiye': 'Turkey'})
life_2022['Country'] = life_2022['Country'].str.strip().replace({'Turkiye': 'Turkey', 'Türkiye': 'Turkey'})
crime_country['Country'] = crime_country['Country'].str.strip().replace({'Turkiye': 'Turkey', 'Türkiye': 'Turkey'})

df = (
    happiness_2022
    .merge(school_2022, on='Country', how='left')
    .merge(life_2022, on='Country', how='left')
    .merge(crime_country, on='Country', how='left')
)

# # There are some missing values and these values are filled with mean of that column that get without Nan

df = df.fillna(df.mean(numeric_only=True))

"""## STATİSTİCS
* You can see the statistical values ( min ,max, mean, std) for the Happiness, Education, Life Expectancy and Crime Index for globaly
* You can see the exact values for the Turkey

"""

print (df.describe())

turkey_df = df[df["Country"] == "Turkey"]
display(turkey_df)

"""Z - SCORE VALUES
* Turkey’s happiness score is 0.75 standard deviations below the global average	This indicates lower-than-average life satisfaction compared to other countries in 2022.
*	Turkey’s education rate is very close to the global mean.	Slightly above average, but not a strong deviation.
* Turkey’s life expectancy is moderately above the global average. Suggests relatively strong health and living standards.
* Turkey’s crime index is more than 1 standard deviation below the global mean.	This implies significantly lower perceived crime compared to many countries.




"""

# Z-score values were calculated using global means and standard deviations to
# understand Turkey’s position within the global distribution
z_cols = ["Happiness_2022", "Education_2022", "LifeExp_2022", "CrimeIndex_2022"]

z_scores = (df[z_cols] - df[z_cols].mean()) / df[z_cols].std()
df_z = df[["Country"]].join(z_scores)

turkey_z = df_z[df_z["Country"] == "Turkey"]
display(turkey_z)

## This is the visual representation of the z-score values
z_scores_no_country = (turkey_z.drop(columns="Country").iloc[0])
z_scores_no_country.plot(kind="bar")
plt.axhline(0, color="black", linewidth=1)
plt.title("Turkey's Z-Scores Relative to Global Distribution (2022)")
plt.ylabel("Z-score")
plt.show()

"""## VİSUALİZATİON
* To examine Turkey’s relative position in a global context, histograms of the Crime Index, Happiness Score, Education Rate, and Life Expectancy for the year 2022 were constructed using data from all available countries. Turkey’s observed value for each indicator was highlighted with a red dashed vertical line.
* The purpose of this visualization is to assess Turkey’s standing relative to the global distribution rather than focusing solely on its absolute values. Since the analysis concentrates on a single country and a single year, comparing Turkey’s indicators against worldwide patterns provides a more meaningful benchmark for interpretation.

RESULTS
* Crime Index - In the Crime Index distribution, Turkey’s value is positioned well to the left of the global mean, indicating that Turkey’s perceived crime level is substantially lower than that of many countries worldwide.

* Happiness - In the Happiness distribution, Turkey appears slightly below the global average, suggesting that overall life satisfaction in Turkey is lower than the world mean in 2022.

* Education - Turkey’s education indicator is located close to the center of the global distribution, implying that Turkey’s education level is broadly comparable to the global average.

* Life Expectancy - In the Life Expectancy distribution, Turkey lies to the right of the global average, reflecting relatively strong health outcomes and a higher-than-average life expectancy compared to many countries.
"""

import seaborn as sns
turkey = df[df["Country"] == "Turkey"].iloc[0]

turkey_crime = turkey["CrimeIndex_2022"]
turkey_happiness = turkey["Happiness_2022"]
turkey_education = turkey["Education_2022"]
turkey_lifeexp = turkey["LifeExp_2022"]

plt.figure(figsize=(8,5))
sns.histplot(df["CrimeIndex_2022"],   bins=30)
plt.axvline(  turkey_crime,   color="red", linestyle="--", linewidth=2,  label="Turkey")

plt.title("Global Crime Index Distribution (2022)")
plt.xlabel("Crime Index")
plt.ylabel("Number of Countries")
plt.legend()
plt.show()

plt.figure(figsize=(8,5))
sns.histplot( df["Happiness_2022"], bins=30)
plt.axvline( turkey_happiness,  color="red",  linestyle="--",  linewidth=2,  label="Turkey")

plt.title("Global Happiness Distribution (2022)")
plt.xlabel("Happiness Score")
plt.ylabel("Number of Countries")
plt.legend()
plt.show()

plt.figure(figsize=(8,5))
sns.histplot( df["Education_2022"],  bins=30)
plt.axvline( turkey_education, color="red", linestyle="--",  linewidth=2,  label="Turkey")

plt.title("Global Education Rate Distribution (2022)")
plt.xlabel("Education Rate")
plt.ylabel("Number of Countries")
plt.legend()
plt.show()

plt.figure(figsize=(8,5))
sns.histplot( df["LifeExp_2022"], bins=30)
plt.axvline( turkey_lifeexp, color="red", linestyle="--", linewidth=2, label="Turkey")

plt.title("Global Life Expectancy Distribution (2022)")
plt.xlabel("Life Expectancy (Years)")
plt.ylabel("Number of Countries")
plt.legend()
plt.show()

"""## CRIME VS OTHER DATAS (VİSİUAL)

Happines vs Crime

* The scatter plot displays the distribution of countries based on their happiness scores and crime index values.

* The regression line represents the global linear relationship between happiness and crime perception. -The downward line indicates a negative relationship between happiness and crime perception (GLOBALLY).

* Turkey is highlighted with a larger marker for direct comparison with the global pattern.
"""

plt.figure(figsize=(7,5))
sns.scatterplot( data=df,  x="Happiness_2022",  y="CrimeIndex_2022",  alpha=0.5)
sns.regplot( data=df,  x="Happiness_2022",  y="CrimeIndex_2022",  scatter=False)

sns.scatterplot( data=df[df["Country"] == "Turkey"], x="Happiness_2022", y="CrimeIndex_2022", s=200,  label="Turkey")

plt.title("Happiness vs Crime Index (2022) — Turkey Highlighted")
plt.xlabel("Happiness Score (2022)")
plt.ylabel("Crime Index (2022)")
plt.legend()
plt.show()

"""EDUCATION VS CRIME

* The scatter plot displays the distribution of countries based on their education scores and crime index values.

* The regression line represents the global linear relationship between education and crime perception.

* Turkey is highlighted with a larger marker for direct comparison with the global pattern.
"""

plt.figure(figsize=(7,5))
sns.scatterplot( data=df, x="Education_2022", y="CrimeIndex_2022",  alpha=0.5)
sns.regplot( data=df, x="Education_2022",  y="CrimeIndex_2022",  scatter=False)

sns.scatterplot( data=df[df["Country"] == "Turkey"],  x="Education_2022",  y="CrimeIndex_2022",  s=200,  label="Turkey")

plt.title("Education vs Crime Index (2022) — Turkey Highlighted")
plt.xlabel("Education Rate (2022)")
plt.ylabel("Crime Index (2022)")
plt.legend()
plt.show()

"""LIFE EXPECTANCY VS CRIME
* The scatter plot displays the distribution of countries based on their Life Expectancy scores and crime index values.

* The regression line represents the global linear relationship between Life Expectancy and crime perception. -The downward line indicates a negative relationship between Life Expectancy and crime perception (GLOBALLY).

* Turkey is highlighted with a larger marker for direct comparison with the global pattern.
"""

plt.figure(figsize=(7,5))
sns.scatterplot(  data=df,  x="LifeExp_2022",  y="CrimeIndex_2022",  alpha=0.5)
sns.regplot(  data=df,  x="LifeExp_2022",  y="CrimeIndex_2022",  scatter=False)

sns.scatterplot(  data=df[df["Country"] == "Turkey"], x="LifeExp_2022", y="CrimeIndex_2022",  s=200,  label="Turkey")

plt.title("Life Expectancy vs Crime Index (2022) — Turkey Highlighted")
plt.xlabel("Life Expectancy (2022)")
plt.ylabel("Crime Index (2022)")
plt.legend()
plt.show()

"""HEAT MAP

This correlation heatmap summarizes correlation coefficients between happiness, education, life expectancy, and crime score for the year 2022. The values range from −1 to +1, where negative values indicate negative relationships and positive values indicate direct relationships.
"""

corr_matrix = df[
    ["Happiness_2022", "Education_2022", "LifeExp_2022", "CrimeIndex_2022"]
].corr()

sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Heatmap of Social Indicators and Crime (2022)")
plt.show()

"""## RATIO COMPARISON
 Happiness, education, and life expectancy values for Turkey were divided by the Crime Index to create ratio-based indicators.

 This approach helps compare social indicators relative to crime perception, rather than looking at their absolute values alone.

*  Education per Crime (3.20): Education appears strong relative to Turkey’s crime perception level.
* Life Expectancy per Crime (2.42): Health outcomes are also relatively strong compared to perceived crime.
* Happiness per Crime (0.15): Happiness remains relatively low despite low crime perception.
"""

happiness_per_crime = turkey["Happiness_2022"] / turkey["CrimeIndex_2022"]
education_per_crime = turkey["Education_2022"] / turkey["CrimeIndex_2022"]
lifeexp_per_crime   = turkey["LifeExp_2022"] / turkey["CrimeIndex_2022"]

ratio_table = pd.DataFrame({
    "Happiness_per_Crime": [happiness_per_crime],
    "Education_per_Crime": [education_per_crime],
    "LifeExp_per_Crime": [lifeexp_per_crime]
})

print (display(ratio_table))

ratio_table.T.plot(kind="bar", legend=False)
plt.title("Social Indicators per Crime Index (Turkey, 2022)")
plt.ylabel("Ratio Value")
plt.show()

"""## RESEARCH QUESTIONS / HYPOTHESIS TESTING

1- To what extent does a higher education rate contribute to a reduction in crime perception for Turkey?

* H₀ (Null hypothesis):
Given the global relationship between education and crime perception, Turkey’s observed crime index is not lower than the value predicted by its education level.

* H₁ (Alternative hypothesis):
Given the global relationship between education and crime perception, Turkey’s observed crime index is lower than the value predicted by its education level.
"""

from scipy.stats import pearsonr, spearmanr

pearson_corr, pearson_p = pearsonr( df["Education_2022"], df["CrimeIndex_2022"])
spearman_corr, spearman_p = spearmanr( df["Education_2022"],  df["CrimeIndex_2022"])

print("Pearson r:", round(pearson_corr, 3), "p-value:", round(pearson_p, 4))
print("Spearman r:", round(spearman_corr, 3), "p-value:", round(spearman_p, 4))

if pearson_p < 0.05:
    print("Significant global relationship")
else:
    print("No significant global relationship")

X = df[["Education_2022"]]
y = df["CrimeIndex_2022"]

model = LinearRegression()
model.fit(X, y)

turkey_row = df[df["Country"] == "Turkey"]
turkey_actual = turkey_row["CrimeIndex_2022"].values[0]

turkey_predicted = model.predict(turkey_row[["Education_2022"]])[0]

residual = turkey_actual - turkey_predicted

print("Turkey Actual Crime Index:", round(turkey_actual, 2))
print("Turkey Predicted Crime Index (Education-based):", round(turkey_predicted, 2))
print("Residual:", round(residual, 2))

if residual < 0:
    print("Reject H₀ ")
else:
    print("Fail to reject H₀")

"""2- Is there a significant negative relationship between happiness levels and the crime index?

* H₀ (Null Hypothesis)
Given the global relationship between happiness and crime perception, Turkey’s observed crime index is not lower than the value predicted by its happiness level.


* H₁ (Alternative Hypothesis)
Given the global relationship between happiness and crime perception, Turkey’s observed crime index is lower than the value predicted by its happiness level.
"""

pearson_corr, pearson_p = pearsonr(df["Happiness_2022"],  df["CrimeIndex_2022"])
spearman_corr, spearman_p = spearmanr( df["Happiness_2022"],  df["CrimeIndex_2022"])

print("Pearson r:", round(pearson_corr, 3), "p-value:", round(pearson_p, 4))
print("Spearman r:", round(spearman_corr, 3), "p-value:", round(spearman_p, 4))

if pearson_p < 0.05 and pearson_corr < 0:
    print("Significant negative global relationship")
else:
    print("No significant negative global relationship")

X = df[["Happiness_2022"]]
y = df["CrimeIndex_2022"]

model = LinearRegression()
model.fit(X, y)

turkey_row = df[df["Country"] == "Turkey"]
turkey_actual = turkey_row["CrimeIndex_2022"].values[0]

turkey_predicted = model.predict(  turkey_row[["Happiness_2022"]])[0]

residual = turkey_actual - turkey_predicted

print("Turkey Actual Crime Index:", round(turkey_actual, 2))
print("Turkey Predicted Crime Index (Happiness-based):", round(turkey_predicted, 2))
print("Residual (Actual - Predicted):", round(residual, 2))

if residual < 0:
    print("Reject H₀ ")
else:
    print("Fail to reject H₀")

"""3- How does life expectancy, as an indicator of overall health and social well-being, influence crime levels?

* H₀ (Null Hypothesis)
Given the global relationship between life expectancy and crime perception, Turkey’s observed crime index is not lower than the value predicted by its life expectancy level.

* H₁ (Alternative Hypothesis)
Given the global relationship between life expectancy and crime perception, Turkey’s observed crime index is lower than the value predicted by its life expectancy level.
"""

pearson_corr, pearson_p = pearsonr( df["LifeExp_2022"],  df["CrimeIndex_2022"])
spearman_corr, spearman_p = spearmanr( df["LifeExp_2022"],  df["CrimeIndex_2022"])

print("Pearson r:", round(pearson_corr, 3), "p-value:", round(pearson_p, 4))
print("Spearman r:", round(spearman_corr, 3), "p-value:", round(spearman_p, 4))

if pearson_p < 0.05 and pearson_corr < 0:
    print("Significant negative global relationship")
else:
    print("No significant negative global relationship")

X = df[["LifeExp_2022"]]
y = df["CrimeIndex_2022"]

model = LinearRegression()
model.fit(X, y)

turkey_row = df[df["Country"] == "Turkey"]
turkey_actual = turkey_row["CrimeIndex_2022"].values[0]

turkey_predicted = model.predict( turkey_row[["LifeExp_2022"]])[0]

residual = turkey_actual - turkey_predicted

print("Turkey Actual Crime Index:", round(turkey_actual, 2))
print("Turkey Predicted Crime Index (LifeExp-based):", round(turkey_predicted, 2))
print("Residual (Actual - Predicted):", round(residual, 2))

if residual < 0:
    print("Reject H₀ ")
else:
    print("Fail to reject H₀")

"""4- Among the key social indicators happiness, education, and health which exerts the strongest impact on reducing crime for Turkey?
* H₀ (Null Hypothesis)
There is no difference in the impact of happiness, education, and life expectancy on crime perception for Turkey.

* H₁ (Alternative Hypothesis)
At least one social indicator (happiness, education, or life expectancy) exerts a stronger impact on reducing crime perception for Turkey than the others.

Crime Index was modeled using happiness, education, and life expectancy as predictors. All variables were standardized (z-scores) so their effects could be compared on the same scale.A linear regression model was fitted using these standardized variables.
"""

X = df[["Happiness_2022", "Education_2022", "LifeExp_2022"]]
y = df["CrimeIndex_2022"]

X_z = (X - X.mean()) / X.std()
y_z = (y - y.mean()) / y.std()

model = LinearRegression()
model.fit(X_z, y_z)

coefficients = pd.Series( model.coef_,  index=X.columns)

print(coefficients)

strongest = coefficients.abs().idxmax()
print("\nStrongest impact on reducing crime:", strongest)

if coefficients.abs().nunique() > 1:
    print("Reject H₀ - One indicator has a stronger impact")
else:
    print("Fail to reject H₀")

"""# MACHINE LEARNİNG MODELS
Supervised machine learning techniques were applied to analyze the relationship between social well-being indicators and crime perception. The objective was to evaluate how happiness, education, and life expectancy can be used to predict the Crime Index and to compare the relative performance of different regression models.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor


X = df[["Happiness_2022", "Education_2022", "LifeExp_2022"]]
y = df["CrimeIndex_2022"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

"""Linear Regression

* Used as a baseline model to understand the linear relationship between social indicators and crime perception.

* The model showed limited predictive performance, indicating that crime perception cannot be explained well by a simple linear relationship.

* Served as a reference point for comparing more complex models.
"""

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

# Calculate Mean Squared Error and then take the square root for RMSE
mse_lr  = mean_squared_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
mae_lr  = mean_absolute_error(y_test, y_pred_lr)
r2_lr   = r2_score(y_test, y_pred_lr)

print("Linear Regression")
print("RMSE:", rmse_lr)
print("MAE :", mae_lr)
print("R2  :", r2_lr)

"""k-Nearest Neighbors (kNN) Regression

* Applied to capture local and non-linear patterns in the data.

* Feature scaling was performed before training due to the distance-based nature of kNN.

* The model did not significantly improve prediction accuracy compared to Linear Regression, suggesting that nearby countries with similar indicators do not always share similar crime perception levels.
"""

knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

mse_knn = mean_squared_error(y_test, y_pred_knn)
rmse_knn = np.sqrt(mse_knn)
mae_knn  = mean_absolute_error(y_test, y_pred_knn)
r2_knn   = r2_score(y_test, y_pred_knn)

print("\nkNN Regression")
print("RMSE:", rmse_knn)
print("MAE :", mae_knn)
print("R2  :", r2_knn)

"""Decision Tree Regression
* Used to model non-linear relationships through rule-based splits.

* A shallow tree was selected to reduce overfitting.

* The results showed slight improvements in interpretability but limited gains in prediction accuracy.
"""

dt = DecisionTreeRegressor(max_depth=3, random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

mse_dt = mean_squared_error(y_test, y_pred_dt)
rmse_dt = np.sqrt(mse_dt)
mae_dt  = mean_absolute_error(y_test, y_pred_dt)
r2_dt   = r2_score(y_test, y_pred_dt)

print("\nDecision Tree")
print("RMSE:", rmse_dt)
print("MAE :", mae_dt)
print("R2  :", r2_dt)

"""* None of the models achieved high predictive accuracy, which is expected due to the subjective and complex nature of crime perception.

* the models provided more explanatory insights than precise predictions.

* The analysis highlights, social well-being indicators alone are insufficient to fully predict crime perception.
"""

results = pd.DataFrame({
    "Model": ["Linear Regression", "kNN", "Decision Tree"],
    "RMSE": [rmse_lr, rmse_knn, rmse_dt],
    "MAE":  [mae_lr,  mae_knn,  mae_dt],
    "R2":   [r2_lr,   r2_knn,   r2_dt]
})

print(results)

"""* The trained Linear Regression model was used to predict Turkey’s Crime Index based on its happiness, education, and life expectancy values.
* The negative residual indicates that Turkey’s actual crime perception is significantly lower than what the model predicts based on its social well-being indicators.
* This result suggests that Turkey performs better than expected in terms of crime perception when compared to countries with similar social indicator levels.
"""

turkey = df[df["Country"] == "Turkey"]
X_tr = turkey[["Happiness_2022", "Education_2022", "LifeExp_2022"]]

pred_tr = lr.predict(X_tr)[0]
actual_tr = turkey["CrimeIndex_2022"].values[0]

print("\nTurkey Actual :", actual_tr)
print("Turkey Predicted:", pred_tr)
print("Residual:", actual_tr - pred_tr)